#!/bin/bash

#desperdiciaría instantOS quickmenu script

all_name='[ALL]'

state="$(mpc -f '' | sed -E '/\[/!d;s/\[//;s/\].*//;s/paused/play/;s/playing/pause/')"

dmenu_args=("-g" "2" "-l" "8" "-h" "-1" "-i" "-r")
dmenu_args_dialog=("-n" "-r" "-i" "-C" "-w" "-1" "-l" "-1" "-bw" "4" "-i")

d_artist() {
    mpc list artist | sort -f | instantmenu -p artist "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(mpc list album artist "$artist")
    if (( ${#albums[@]} > 1 )) ; then
        {
            printf '%s\n' "$all_name"
            printf '%s\n' "${albums[@]}" | sort -f
        } | instantmenu -p album "${dmenu_args[@]}"
    else
        # We only have one album, so just use that.
        printf '%s\n' "${albums[0]}"
    fi
}

d_jump() {
    local format="%position% %title%"
    local extra_format="(%artist% - %album%)"
    local track
    local num_extras

    # If all tracks are from the same artist and album, no need to display that
    num_extras=$(mpc playlist -f "$extra_format" | sort | uniq | wc -l)
    (( num_extras == 1 )) || format+=" $extra_format"

    track=$(mpc playlist -f "$format" | instantmenu -p track "${dmenu_args[@]}")
    printf '%s' "${track%% *}"
}

d_playlist() {
    printf '%s' "$(mpc lsplaylists | instantmenu -q 'select playlist' ${dmenu_args_dialog[@]})"
}

case "$(echo "$state"$'\nlibrary\nplaylists\njump to' | instantmenu -q 'select' "${dmenu_args_dialog[@]}")" in
    "library")
        artist=$(d_artist)
        [[ $artist ]] || exit 1

        album=$(d_album "$artist")
        [[ $album ]] || exit 2

        mpc clear
        if [[ $album == "$all_name" ]]; then
            mpc find artist "$artist" | sort | mpc add
        else
            mpc find artist "$artist" album "$album" | sort | mpc add
        fi
        mpc play >/dev/null
        ;;
    "playlists")
        playlist="$(d_playlist)"
	[ -z "$playlist" ] && exit
        mpc clear
        mpc load "$playlist"
        mpc play
        ;;
    "jump to")
        mpc play "$(d_jump)" >/dev/null
        ;;
    "play"|"pause")
        mpc $state
        ;;
esac
