#!/bin/bash

# instantOS quickmenu script

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

dmenu="instantmenu"
dmenu_args=("-p" "       " "-h" "-1" "-l" "8" -g 3 )

pass_actions="copy pass
type pass
get an info field
show all info$(pacman -Q pass-otp > /dev/null && echo $'\ncopy otp')"

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | $dmenu "${dmenu_args[@]}"  -q 'search passwords')
[[ -n $password ]] || exit

action=$($dmenu "${dmenu_args[@]}"  -q 'select action'<<<"$pass_actions")

case $action in
	'copy pass')
		pass show -c "$password" 2>/dev/null;;
	'type pass')
		pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
		;;
	'get an info field')
		field="$(pass $password | awk -F ':' '/:/ {print $1}' | $dmenu "${dmenu_args[@]}"  -q 'select field')"
		[ -z "$field" ] && exit 0
		info="$(pass $password | grep "^$field")"
		option="$(echo $'copy\ntype\nexit' | $dmenu "${dmenu_args[@]}"  -p "$info " -q 'choose option')"
		case $option in
			'copy') awk "/^$field/"' {print $NF}'<<<"$info" | xclip -selection clipboard;;
			'type') awk "/^$field/"' {print $NF}'<<<"$info" | xdotool type --clearmodifiers --file -;;
			*) exit 0;;
		esac ;;
	'show all info')
		pass $password | tail -n+2 | $dmenu "${dmenu_args[@]}"  -l -1 -q 'hit enter to exit';;
	'copy otp')
		pass otp -c $password || echo -n '' | $dmenu "${dmenu_args[@]}"  -p "That password does not have an otp " -q 'error';;
esac
